const SHARPEN_KERNEL: number[][] = [
  [0, -1, 0],
  [-1, 5, -1],
  [0, -1, 0],
];

export const CONFIG = {
  DISPLAY: {
    WIDTH: 1280,
    HEIGHT: 720,
  },
  SHARPEN: {
    ENABLED: true,
    KERNEL: SHARPEN_KERNEL,
  },
  FACE_SIZE: {
    FAR_THRESHOLD: 80,
    NEAR_THRESHOLD: 260,
  },
  BRIGHTNESS: {
    DARK_THRESHOLD: 60,
    BRIGHT_THRESHOLD: 190,
  },
  POSITION: {
    CENTER_TOLERANCE: 0.15, // 15%
  },
  TIMING: {
    STEP1_HOLD_SECONDS: 2.0,
    STEP2_YAW_HOLD_SECONDS: 1.2,
    STEP2_PITCH_HOLD_SECONDS: 1.0,
    BLINK_MIN_SECONDS: 0.3,
    MOUTH_OPEN_MIN_SECONDS: 0.6,
    MOUTH_OPEN_MAX_SECONDS: 2.0,
    MOUTH_CLOSE_MIN_SECONDS: 0.6,
  },
  SMOOTHING: {
    BOX_EMA_ALPHA: 0.3,
    YAW_EMA_ALPHA: 0.25,
    PITCH_EMA_ALPHA: 0.25,
    BLINK_BASE_EMA_ALPHA: 0.1,
    MOUTH_BASE_EMA_ALPHA: 0.1,
  },
  THRESHOLDS: {
    YAW_ENTER_DEG: 8.0,
    YAW_EXIT_DEG: 5.0,
    YAW_ZERO_UPDATE_BAND: 8.0,
    PITCH_ENTER_DEG: 8.0,
    PITCH_EXIT_DEG: 5.0,
    PITCH_ZERO_UPDATE_BAND: 6.0,
    BLINK_THRESH_FRACTION: 0.72,
    MOUTH_OPEN_DELTA: 0.12,
  },
  CAMERA: {
    MIRRORED_INPUT: true,
  },
  LANDMARKS: {
    SHOW_IN_STEP2: true,
  },
} as const;
