import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "cropperjs/dist/cropper.css";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

import Providers from "./providers";
import ResumeGate from "./ResumeGate";
import RouteTracker from "./RouteTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.ico?v=2" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh`}
      >
        <Providers>
          <Suspense fallback={null}>
            {children}
            <RouteTracker ttlMin={30} />
            <ResumeGate ttlMin={30} enabled />
          </Suspense>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
